fully separate view implementation from PentagoLib
sersajur/QPentago pull request #13
Opened 2018-10-21 00:39 UTC by Youw

2018-10-21 02:04 UTC, Youw commented
This also fixes a Linux build

2018-10-22 16:50 UTC, GasperPaul requested changes
I'm ok with this conceptually.

My only concern right now is why are we having this completely weird folder structure? There are two different lib folders (`PentagoLib` and `pentagolib`). I still don't follow the logic for that separation. Can we have that discussed and sorted in this PR?

2018-10-22 19:07 UTC, Youw commented
This PR is also about renaming `pentagolib`->`PentagoLib`.

So we have:
```
PentagoLib /
    include/PentagoLib
        ...// some .h file
    ... // some .cpp files
    ... // some private headers <not in our case - not yet>
```

It is a known practice, to separate your public headers to a separate folder (in our case `include/PentagoLib`). So it gives us:
- ability to specify `include` folder as include path for your target, and separate your private headers, if there are any; (there are also other advantages, that I can come up with)
- now the users of this library/target has to explicitly specify library, where specific header should be found: `#include <PentagoLib/Game.h>`; (remember how boost does this: `#include <boost/something.hpp>`)

I think this one of the possibles approaches for project structure, as an opposite to simple "all cpp/h in a single folder" (which has other advantages sometime).

2018-10-23 19:06 UTC, GasperPaul commented
> This PR is also about renaming `pentagolib`->`PentagoLib`.

Now, I'm pro all of that. I, personally, would prefer lowercase, but it's beside the point. I am more worried about why exactly we have the following folder structure at a higher level:

    src /
        PentagoLib /
            include /
                <all the header>
            src /
                Game.cpp
            test
        WidgetsApp
        pentagolib / 
            src /
                <all other cpp>
            test
            CMakeLists.txt

I have a few issues with this, main being why are we have thouse two top level different case versions of pentagolib folder, one with headers and one cpp, other with all the cpps. It's clearly either a bad name choosen for one (because OS differences?), or a case of not moving all the files. They existed before this PR, but I think we should fix it now, while we're at it.

I propose we move everything into PentagoLib and be done with this. Or am I missing something?

2018-10-23 19:14 UTC, GasperPaul commented
I would also argue that we should have either

    PentagoLib / include
        / src
    WidgetsApp / include
        / src

or
    src / PentagoLib
        / WidgetsApp
    include / PentagoLib
        / WidgetsApp

But this is not the main contention point for me.

2018-10-23 19:31 UTC, Youw commented
Your second suggestion has a huge design flaw - you're mixing sources of two separate libraries, which is conceptually a bad idea.

In the first option we're loosing the ability to separate "headers namespace" for different libraries.
E.g., right now we can:

    #include <PentagoLib/Game.h>

With you suggestion - it is not possible.

There is no reason to keep *.h and *.cpp files in a separate folder, for "just to keep them separate",
so practically, `PentagoLib/include` + `PentagoLib/src` is no better than `PentagoLib/<everything is here>`.
But putting all public headers under `PentagoLib` sub-folder gives us a powerful advantage: now we can have `#include <PentagoLib/Board.h>`  and (yes, I'm making this up, just get the idea)`#include <ChessLib/Board.h>` in the same .cpp file without any name conflicts or unexpected compiler errors.

@sersajur, what's you opinion?

2018-10-23 21:15 UTC, Youw commented
Removing tom-most `src` is not a good idea.
It separates our own "the code" from everything else (3d-party libraries, top-most build scripts, tools, deployer scripts, etc.).

> In scenario one, we add public headers in `PentagoLib/include`

And you no longer can have something like `#include <PentagoLib/Game.h>`.
Either `#include <Game.h>`, either `#include <PentagoLib/include/Game.h>` which looks so weird.

Also, don't forget, that you shouldn't have access to headers of the target, that is not explicitly listed as "required" by your current project.

2018-10-23 22:02 UTC, Youw commented
Finally get rid of lower case library. I didn't see it exists.

2018-10-23 22:02 UTC, GasperPaul approved these changes

2018-11-16 00:10 UTC, sersajur commented on src/PentagoLib/test/main.cpp
> +int main(int argc, char* argv[])
This file is unused, we use predefined by googletest main file.

2018-11-16 00:13 UTC, sersajur reviewed
Good changes, I like the way you choose naming.

2018-11-16 00:41 UTC, sersajur approved these changes

2018-11-21 02:11 UTC, merged